### ISSUE TITLE
Can you povide the paper? 

### ISSUE THREAD

**Issue by shenminyin** [Bosen-Lian/project_offpolicyDTanta#1]
Can you povide the paper?

**Comment by Bosen-Lian** [comment]
Here is the link

https://www.researchgate.net/publication/373587909_Off-policy_inverse_Q-learning_for_discrete-time_antagonistic_unknown_systems

**Comment by shenminyin** [comment]
The simulation results are not quite right, k-ke is not equal to 0,and the norm of Q is too big to the system.Moreover the results  is not match the paper.

**Comment by shenminyin** [comment]
By the way,thank you very much for providing the code to give me a better understanding of offpolicy
